version: '3.7'
#Remove comments when we need rasa or a database in the system 
services:
    rasa:
        image: rasa/rasa:latest-full
        container_name: rasa
        ports:
        - "5005:5005"
        volumes:
        - "./rasa-app-data/models:/app/models"
        - "./rasa-app-data/logs:/app/logs"
        command: "run --enable-api --debug"
    project-x-frontend:
        build: ./training-interface
        restart: on-failure
        container_name: project-x-frontend
        ports:
            - "3000:3000"
        volumes:
            - ./training-interface:/training-interface
        environment:
        # For some reason for react env variables to be imported properly
        # you need the REACT_APP prefix & the name can't contain underscores.
        - REACT_APP_RASAENDPOINT=${RASA_ENDPOINT}
        depends_on:
        - rasa
        - server
        restart: on-failure
    server:
        build: ./server
        restart: always
        container_name: server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/server
        environment:
            - RASA_ENDPOINT=${RASA_ENDPOINT}
            - SERVER_PORT=${SERVER_PORT}
            - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
            # script to wait for mongo to be fully up & running
            - WAIT_HOSTS=db:27017
        depends_on:
            - db
            - rasa
        restart: on-failure
    db:
        image: mongo:latest
        volumes:
            - $DATABASE_DATA:/$DATABASE_DATA
            - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        environment:
            # to connect from cmd line run (read / write user) for root access use root user
            # mongo --port 27017 -u "user" -p "password" --authenticationDatabase "db"
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        restart: on-failure
        expose:
            - ${MONGO_PORT}
