version: '3.7'
#Remove comments when we need rasa or a database in the system 
services:
    rasa:
        image: rasa/rasa:latest-full
        container_name: rasa
        ports:
        - "5005:5005"
        volumes:
        - "./rasa-app-data/models:/app/models"
        - "./rasa-app-data/logs:/app/logs"
        command: "run --enable-api --debug"
    project-x-frontend:
        build: ./training-interface
        restart: on-failure
        container_name: project-x-frontend
        ports:
            - "3000:3000"
        volumes:
            - ./training-interface:/training-interface
        environment:
        - RASA_ENDPOINT=${RASA_ENDPOINT}
        depends_on:
        - rasa
        - db
        restart: on-failure
    db:
        image: mongo:latest
        volumes:
            - $DATABASE_DATA:/$DATABASE_DATA
            - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        environment:
            # to connect from cmd line run (read / write user) for root access use root user
            # mongo --port 27017 -u "user" -p "password" --authenticationDatabase "db"
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        restart: on-failure
        expose:
            - "27017"
